ALTER TABLE action
ADD COLUMN IF NOT EXISTS operation_id TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS url TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS method TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS path_param_schema JSONB,
ADD COLUMN IF NOT EXISTS query_param_schema JSONB,
ADD COLUMN IF NOT EXISTS body_param_schema JSONB,
ADD COLUMN IF NOT EXISTS body_type TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS function_def JSONB NOT NULL DEFAULT '{}';
